# Generated by Django 5.0 on 2026-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='curLat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='curLong',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='curLat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='curLong',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='currentLocation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
