# Generated by Django 6.0.1 on 2026-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_jobseeker_curlat_jobseeker_curlong_recruiter_curlat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='curLat',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='curLong',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='curLat',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='curLong',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='currentLocation',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
