# Generated by Django 5.0 on 2026-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
