# Generated by Django 5.0 on 2026-02-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jobSeekerIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.jobseeker')),
                ('recruiterIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.recruiter')),
            ],
        ),
    ]
